news/urls.py
from django.urls import path
from .views import *

app_name = 'news'

urlpatterns = [
    path('homepage_news/', homepage_news, name="homepage_news"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("articoli/", articoloDetailView, name="articolo_detail"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("giornalisti/", giornalistaDetailView, name="giornalista_detail"),
    path("lista_articoli/<int:pk>", lista_articoli_giornalisti, name="lista_articoli"),
    path("lista_articoli/", lista_articoli_giornalisti, name="lista_articoli"),
    path("lista_giornalisti/", lista_giornalisti, name="lista_giornalisti"),
    path("lista_giornalisti/<int:pk>", lista_giornalisti, name="lista_giornalisti"),
    path("query_base/", query_base, name="query_base"),
    path('', index_news, name='index_news'),
    path("lista_giornalisti_api/", giornalisti_lista_api, name="list_giornalisti_api"),
    path("giornalista_api/<int:pk>", giornalista_api, name="giornalista_api"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace = "prima_app")),
    path('', index, name = 'index'),
    path('seconda_app/', include("seconda_app.urls", namespace = "seconda_app")),
    path('news/', include("news.urls", namespace = "news")),
    path('prova_pratica_1/', include("prova_pratica_1.urls", namespace = "prova_pratica_1")),
    path('voti/', include("voti.urls", namespace = "voti")),
    path('products/', include("products.urls", namespace = "products")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/', include('forms_app.urls', namespace = "forms_app")),
]

prova_pratica_1/urls.py
from django.urls import path
from .views import *


app_name = "prova_pratica_1"
urlpatterns = [
    path('indexP', indexP, name = 'indexP'),
    path('somma', somma, name = 'somma'),
    path('media', media, name = 'media'),
    path('voti', voti, name = 'voti'),

]

voti/urls.py
from django.urls import path
from .views import *


app_name = "voti"
urlpatterns = [
    path('indexV', indexV, name = 'indexV'),
    path('view_a', view_a, name = 'view_a'),
    path('view_b', view_b, name = 'view_b'),
    path('view_c', view_c, name = 'view_c'),
    path('view_d', view_d, name = 'view_d'),
]

prova_pratica_1/views.py
from django.shortcuts import render
import random

# Create your views here.
def indexP(request):
    return render(request, "indexP.html")

def somma(request):
    var1 = random.randint(1,10)
    var2 = random.randint(1,10)
    somma = var1+var2
    context = {
        'var1' : var1,
        'var2' : var2,
        'somma' : somma,
    }
    return render(request, "somma.html", context)

def media(request):
    lista = []
    i = 0
    somma = 0
    for i in range (30) :
        n=random.randint(1,10)
        lista.append(n)
        somma+=n
    media = somma/30

    context = {  
        'lista' : lista,
        'media' : media,
    }
    return render(request, "media.html", context)

def voti(request):
    
    context = {
        'dizionario' : {'studente1': 8, 'studente2': 6, 'studente3' : 7, 'studente4' : 4},
    }

    return render(request, "voti.html", context)

voti/views.py
from django.shortcuts import render

# Create your views here.

diz_studenti = {
           'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7,4),("Storia",7,4),("Geografia",5,7)],
           'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9,0),("Storia",8,2),("Geografia",8,1)],
           'Nicola Spina':[("Matematica",7,2),("Italiano",6,2),("Inglese",4,3),("Storia",8,2),("Geografia",8,2)]
        } 

def indexV(request):
    return render(request, "indexV.html")

def view_a(request):
    context = {
       'materie': ["Matematica","Italiano","Inglese","Storia","Geografia"] 
    }
    return render(request, "view_a.html", context)

def view_b(request):
    context = {
        'diz_studenti' : diz_studenti,
    }
    return render(request, "view_b.html", context)

def view_c(request):
    i = 0
    j = 0
    somma = 0
    lista = []
    for studenti,materie in diz_studenti:
        somma=0
        for materia,voto in materie:
            somma += voto
        media = somma/materia
        lista.append(media)
    context = {  
    'lista' : lista,
    }
    return render(request, "view_c.html", context)
    
def view_d(request):

    return render(request, "view_d.html", context)

prova_pratica_1/templates/indexP.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Index P {%endblock title%}

{%block content%}
    <h1>Index P</h1>
    <li><a href="{% url 'prova_pratica_1:somma'%}">somma</a></li>
    <li><a href="{% url 'prova_pratica_1:media'%}">media</a></li>
    <li><a href="{% url 'prova_pratica_1:voti'%}">voti</a></li>
{%endblock content%}

prova_pratica_1/templates/media.html
{% extends "base.html"%}

{%block title%} {{block.super}} | media {%endblock title%}

{%block content%}

    <!--<b>media = {{media}}</b><br/>-->


    {% for x in lista %}
        <i>{{ forloop.counter }}</i> : {{ x }}<br>
    {% endfor %}

    {% if media > 6 %}
        <b  style="color:green" >media = {{media}}</b><br/>
    {% endif %}

    {% if media < 6 %}
        <b  style="color:red" >media = {{media}}</b><br/>
    {% endif %}

{%endblock content%}

prova_pratica_1/templates/somma.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Es if {%endblock title%}

{%block content%}
    <b>var1 = {{var1}}</b><br/>
    <b>var2 = {{var2}}</b><br/>
    <b>somma = {{somma}}</b><br/>

    {% if var1 < var2 %}
        <p style="color:red"><i>{var1} è minore di {var2}</i></p>
    {% endif %}
    
    {% if var1 > var2 %}
        <p style="color:green"><i>{var1} è maggiore di {var2}</i></p>
    {% endif %}

    {% if var1 == var2 %}
        <p><i>{var1} è uguale a {var2}</i></p>
    {% endif %}
{%endblock content%}

prova_pratica_1/templates/voti.html
{% extends "base.html"%}

{%block title%} {{block.super}} | voti {%endblock title%}

{%block content%}

<table>
    {% for studente,voto in dizionario.items %}
    <tr>   
        <th> {{ studente }} </th>
    </tr>
    <tr>
        <td>{{voto}}</td>
    </tr>
    {% endfor %}

</table>



{%endblock content%}