forms_app/urls.py
from django.urls import path
from .views import *

app_name = "forms_app"
urlpatterns = [
    path('contattaci/', contatti, name='contatti'),
    path('lista_contatti/', lista_contatti, name='lista_contatti'),
    path('modifica_contatto/<int:pk>', modifica_contatto, name='modifica_contatto'),
    path('elimina_contatto/<int:pk>', elimina_contatto, name='elimina_contatto'),
]

news/urls.py
from django.urls import path
from .views import *

app_name = 'news'

urlpatterns = [
    path('homepage_news/', homepage_news, name="homepage_news"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("articoli/", articoloDetailView, name="articolo_detail"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("giornalisti/", giornalistaDetailView, name="giornalista_detail"),
    path("lista_articoli/<int:pk>", lista_articoli_giornalisti, name="lista_articoli"),
    path("lista_articoli/", lista_articoli_giornalisti, name="lista_articoli"),
    path("lista_giornalisti/", lista_giornalisti, name="lista_giornalisti"),
    path("lista_giornalisti/<int:pk>", lista_giornalisti, name="lista_giornalisti"),
    path("query_base/", query_base, name="query_base"),
    path('', index_news, name='index_news'),
    path("lista_giornalisti_api/", giornalisti_lista_api, name="list_giornalisti_api"),
    path("giornalista_api/<int:pk>", giornalista_api, name="giornalista_api"),
]

prima_app/urls.py
from django.urls import path
from .views import *


app_name = "prima_app"
urlpatterns = [
    path('homepage', homepage, name = 'homepage'),
    path('welcome', welcome, name = 'welcome'),
    path('lista', lista, name = 'lista'),
    path('chisiamo', chisiamo, name = 'chisiamo'),
    path('variabili', variabili, name = 'variabili'),
    path('', index, name = 'index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace = "prima_app")),
    path('', index, name = 'index'),
    path('seconda_app/', include("seconda_app.urls", namespace = "seconda_app")),
    path('news/', include("news.urls", namespace = "news")),
    path('prova_pratica_1/', include("prova_pratica_1.urls", namespace = "prova_pratica_1")),
    path('voti/', include("voti.urls", namespace = "voti")),
    path('products/', include("products.urls", namespace = "products")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/', include('forms_app.urls', namespace = "forms_app")),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import *


app_name = "seconda_app"
urlpatterns = [
    path('index_2', index_2, name = 'index_2'),
    path('es_if', es_if, name = 'es_if'),
    path('if_else_elif', if_else_elif, name = 'if_else_elif'),
    path('es_for', es_for, name = 'es_for'),

]

voti/urls.py
from django.urls import path
from .views import *


app_name = "voti"
urlpatterns = [
    path('indexV', indexV, name = 'indexV'),
    path('view_a', view_a, name = 'view_a'),
    path('view_b', view_b, name = 'view_b'),
    path('view_c', view_c, name = 'view_c'),
    path('view_d', view_d, name = 'view_d'),
]

templates/base.html
<!doctype html>
 <!-- Includi Font Awesome CSS -->
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% load static %}
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>
  <body>
    <!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="">Primo progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- <ul class="navbar-nav mr-auto"> -->

            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="index.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Prima app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:chisiamo'%}">Chi siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Homepage</a>
                <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Varialibi</a>
                <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
              </div>
            </div>
           
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="index_2.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seconda app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Es if</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Es for</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">If else elif</a>
                </div>
              </div> 

              <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="indexP.html" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                prova_pratica_1
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prova_pratica_1:somma'%}">somma</a>
                <a class="dropdown-item" href="{% url 'prova_pratica_1:media'%}">media</a>
                <a class="dropdown-item" href="{% url 'prova_pratica_1:voti'%}">voti</a>
              </div>
            </div>
             
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="index_news" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  News
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'news:homepage_news'%}">Homepage</a>
                  <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">Lista_articoli</a>
                  <a class="dropdown-item" href="{% url 'news:lista_giornalisti'%}">Lista_giornalisti</a>
                  <a class="dropdown-item" href="{% url 'news:query_base'%}">query_base</a>
                </div>
                </div>
              
             
                <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="indexV" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Voti
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'voti:view_a'%}">Lista materie</a>
                <a class="dropdown-item" href="{% url 'voti:view_b'%}">Registro voti</a>
                <a class="dropdown-item" href="{% url 'voti:view_c'%}">Media voti</a>
                <a class="dropdown-item" href="{% url 'voti:view_d'%}">Voto più alto e più basso</a>
              </div>
            </div>

            <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Contatti
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'forms_app:contatti'%}">Contattaci</a>
              <a class="dropdown-item" href="{% url 'forms_app:lista_contatti'%}">Lista Contatti</a>  
            </div>
             </div>

          <!-- </ul> -->
          
          {% if request.user.is_authenticated %}
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{request.user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{%url 'logout' %}">Esci</a>
            </div>
            </div>

      {%else%}
            <a class="nav-link" href="{% url 'login' %}">Login  </a>
        
      {% endif %}
    
    </nav>
      <div class="container my-4">
        <!--servirà per inserire i contenuti della pagina-->
        {%block content%}
        {%endblock content%}
        <!--servirà per inserire il codice javascript-->
        {%block script%}
        {%endblock script%}
      </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    
    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <ol>
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
        <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
        <li><a href="{% url 'prima_app:chisiamo'%}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
        <li><a href="{% url 'prima_app:index'%}">Index</a></li>
    </ol>
</body>
</html>

templates/index_root.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Index root {%endblock title%}

{%block content%}
    <h1>Index</h1>
    <li><a href="/admin">Pannello admin</a></li>
    <li><a href="{% url 'prima_app:index'%}">Index prima app</a></li>
    <li><a href="{% url 'seconda_app:index_2'%}">Index seconda app</a></li>
    <li><a href="{% url 'news:index_news'%}">Index news</a></li>
    <li><a href="{% url 'voti:indexV'%}">Index voti</a></li>
{%endblock content%}