news/urls.py
from django.urls import path
from .views import *

app_name = 'news'

urlpatterns = [
    path('homepage_news/', homepage_news, name="homepage_news"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("articoli/", articoloDetailView, name="articolo_detail"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
    path("giornalisti/", giornalistaDetailView, name="giornalista_detail"),
    path("lista_articoli/<int:pk>", lista_articoli_giornalisti, name="lista_articoli"),
    path("lista_articoli/", lista_articoli_giornalisti, name="lista_articoli"),
    path("lista_giornalisti/", lista_giornalisti, name="lista_giornalisti"),
    path("lista_giornalisti/<int:pk>", lista_giornalisti, name="lista_giornalisti"),
    path("query_base/", query_base, name="query_base"),
    path('', index_news, name='index_news'),
    path("lista_giornalisti_api/", giornalisti_lista_api, name="list_giornalisti_api"),
    path("giornalista_api/<int:pk>", giornalista_api, name="giornalista_api"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls", namespace = "prima_app")),
    path('', index, name = 'index'),
    path('seconda_app/', include("seconda_app.urls", namespace = "seconda_app")),
    path('news/', include("news.urls", namespace = "news")),
    path('prova_pratica_1/', include("prova_pratica_1.urls", namespace = "prova_pratica_1")),
    path('voti/', include("voti.urls", namespace = "voti")),
    path('products/', include("products.urls", namespace = "products")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forms_app/', include('forms_app.urls', namespace = "forms_app")),
]

news/models.py
from django.db import models

class Giornalista(models.Model):
    """ il modello generico di un giornalista """
    nome = models.CharField(max_length=20)
    cognome = models.CharField(max_length=20)
    anno_di_nascita = models.DateField(blank=True)

    class Meta:
        verbose_name="Giornalista"
        verbose_name_plural="Giornalisti"

    def __str__(self):
        return self.nome + " " + self.cognome

class Articolo(models.Model):
    """ il modello generico di un articolo di news """
    titolo = models.CharField(max_length=100)
    contenuto = models.TextField()
    giornalista = models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")
    data=models.DateField(blank=True)
    visualizzazioni=models.IntegerField(default=0,blank=True)

    def __str__(self):
        return self.titolo

    class Meta:
       verbose_name="Articolo"
       verbose_name_plural="Articoli"

news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Articolo, Giornalista
import datetime
from django.http import JsonResponse
# Create your views here.

def giornalisti_lista_api(request):
    giornalisti=Giornalista.objects.all()
    data={'giornalisti':list(giornalisti.values("pk","nome","cognome"))}
    response=JsonResponse(data)
    return response

def giornalista_api(request,pk):
    try:
        giornalista=Giornalista.objects.get(pk=pk)
        data={ 'giornalista':{
            "nome": giornalista.nome,
            "cognome":giornalista.cognome,
            }
        }
        response=JsonResponse(data)
    except Giornalista.DoesNotExist:
        response=JsonResponse({
          "error":{
              "code":404,
              "message":"Giornalista non trovato"
          }},  
        status=404)
    return response


def homepage_news(request):
    a = ""
    g = ""
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti": giornalisti}
    print(context)
    return render(request, "homepage_news.html", context)

def articoloDetailView(request, pk):
    #articolo = Articolo.objects.get(pk=pk)
    articolo = get_object_or_404(Articolo, pk=pk)
    context = {"articolo": articolo}
    return render(request, "articolo_detail.html", context)

def giornalistaDetailView(request, pk):
    giornalista = get_object_or_404(Giornalista, pk=pk)
    articoli=Articolo.objects.filter(giornalista_id=pk)
    context = {"giornalista": giornalista, "articolo": articoli }
    return render(request, "giornalista_detail.html", context)

    #for art in Articolo.objects.all():
        #a += (art.titolo + "<br>")
        #a.append(art.titolo)
    
    #for gio in Giornalista.objects.all():
        #g += (gio.nome + "<br>")
        #g.append(gio.nome)

    #response = "Articoli:<br>" + a + "<br>Giornalisti:<br>" + g
    #response = str(a) + "<br>" + str(g)
    #print (response)
    
    #return HttpResponse("<h1>" + response + "</h1>")

def lista_articoli_giornalisti(request, pk=None):
    if(pk==None):
        articoli=Articolo.objects.all()
    else:
        articoli=Articolo.objects.filter(giornalista_id=pk)
    context = {
        'articoli': articoli,
        'pk':pk,
    }
    return render(request, 'lista_articoli.html', context)


def lista_giornalisti(request, pk=None):
    if(pk==None):
        giornalisti=Giornalista.objects.all()
    else:
        giornalisti=Giornalista.objects.filter(giornalista_id=pk)
    context = {
        'giornalisti': giornalisti,
        'pk':pk,
    }
    return render(request, 'lista_giornalisti.html', context)

def index_news(request):
    return render(request, "index_news.html")
    
def query_base(request):
    #1. Tutti gli articoli scritti dai gionalisti di un certo cognome:
    articoli_cognome = Articolo.objects.filter(giornalista__cognome='Marinelli')
    
    #2. totale
    numero_totale_articoli = Articolo.objects.count()

    #3. contare il numero di articoli scritti da un gionalista specifico:
    giornalista_1 = Giornalista.objects.get(id=4)
    numero_articoli_giornalista_1 = Articolo.objects.filter(giornalista=giornalista_1).count()

    #4. ordinare gli articoli per numero di visualizzazioni in ordine descrescente:
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')

    #5. tutti gli articoli che non hanno visualizzazioni:
    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni=0)

    #6. articolo più visualizzato
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()

    #7. tutti i giornalisti nati dopo una certa data:
    giornalista_data= Giornalista.objects.filter(anno_di_nascita__gt=datetime.date(1900, 1, 1))

    #8. tutti gli articoli pubblicati in una data specifica:
    articoli_del_giorno=Articolo.objects.filter(data=datetime.date(2023, 1, 1))

    #9 tutti gli articoli pubblicati in un intervallo di date:
    articoli_periodo= Articolo.objects.filter(data__range=(datetime.date(2023, 1, 1), datetime.date(2023, 12, 31)))

    #10 gli articoli scritti da giornalista nati prima del 1980:
    giornalista_nati= Giornalista.objects.filter(anno_di_nascita__lt=datetime.date(1980, 1, 1))
    articoli_giornalista= Articolo.objects.filter(giornalista__in=giornalista_nati)

    #11 il gionalista più giovane:
    giornalista_giovane=Giornalista.objects.order_by('-anno_di_nascita').first()

    #12 il gionalista più anziano:
    giornalista_anziano=Giornalista.objects.order_by('anno_di_nascita').first()

    #13 gli ultmi 5 articoli pubblicati:
    ultimi= Articolo.objects.order_by('-data')[:5]

    #14 tutti gli articoli con un certo numero minimo di visualizzazioni:
    articoli_minime_visualizzazioni= Articolo.objects.filter(visualizzazioni__gte=100)

     #15 tutti gli articoli che contengono una certa parola nel titolo:
    articoli_parola= Articolo.objects.filter(titolo__icontains='importante')

    #16 Articoli pubblicati in un certo mese di  un anno specifico:
    #nota per poter modificare la data di un articolo togliere la proprietà auto_now = True al field data nel model
    #poi dare i comandi makemigration e migrate per riapplicare le modifiche al database
    articoli_mese_anno=Articolo.objects.filter(data__month=1, data__year=2023)

    #17 giornalisti con almeno un articolo con più di 100 visualizzazioni:
    giornalisti_con_articoli_popolari = Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct()

    """
    spiegazione dettagliata:
    Giornalsta.objects : Inizia dalla classe del modello Giornalista.
    .filter(articoli__visualizzazioni__gte=100): Ultilizza il metodo filter() per filtrare i giornalisti
    in base al campo visualizzazione nel modello Articolo. La notazione articoli_visualizzazioni indica
    che si sta seguendo la relazione inversa della classe Giornalista alla classe Articolo attraverso 
    il campo ForeignKey giornalista nel modello Articolo.
    .distinct(): E' un metodo che assicur che i risualtati siano distinti, eliminando eventuali duplicati.
    In questo caso, ciò è utile perchè un gionalista potrebbe essere associato a più articoli che soddisfano 
    il criterio, e vogliono ottenere una volta ogni giornalista che ha scritto almeno un articolo popolare.
    """

    #UTILIZZO DI PIU' CONDIZIONI DI SELEZIONE 
    data = datetime.date(1990, 1, 1)
    visualizzazioni = 50

    #Per mettere in AND le condizioni separarle con la virgola  
    #18 ...scrivi quali articoli vengono selezionati 
    articoli_con_and = Articolo.objects.filter(giornalista__anno_di_nascita__gt=data, visualizzazioni__gte=visualizzazioni)

    #Per mettere in OR le condizioni utlizzare l'operatore Q
    from django.db.models import Q
    #19 ...scrivi quali articoli vengono selezionati 
    articoli_con_or = Articolo.objects.filter(Q(giornalista__anno_di_nascita__gt=data) |Q(visualizzazioni__lte=visualizzazioni))

    #per il NOT(~) utilizzare l'operatore Q
    #20 ... scivi quali articoli vengono selezionati
    articoli_con_not = Articolo.objects.filter(~Q(giornalista__anno_di_nascita__lt=data))
    #oppure il metodo exclude
    articoli_con_not = Articolo.objects.exclude(giornalista__anno_di_nascita__lt=data)



    #creare il dizionario context
    context= {
        'articoli_cognome': articoli_cognome,
        'numero_totale_articoli': numero_totale_articoli,
        'numero_articoli_giornalista_1': numero_articoli_giornalista_1,
        'articoli_ordinati': articoli_ordinati,
        'articoli_senza_visualizzazioni': articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato': articolo_piu_visualizzato,
        'giornalista_data': giornalista_data,
        'articoli_del_giorno': articoli_del_giorno,
        'articoli_periodo': articoli_periodo,
        'articoli_giornalisti':articoli_giornalista,
        'giornalista_giovane': giornalista_giovane,
        'giornalista_anziano': giornalista_anziano,
        'ultimi': ultimi,
        'articoli_minime_visualizzazioni': articoli_minime_visualizzazioni,
        'articoli_parola': articoli_parola,
        'articoli_mese_anno' : articoli_mese_anno,
        'giornalisti_con_articoli_popolari': giornalisti_con_articoli_popolari,
        'articoli_con_and': articoli_con_and,
        'articoli_con_or': articoli_con_or,
        'articoli_con_not':articoli_con_not,
            }

    return render (request, 'query_base.html', context)

news/templates/articolo_detail.html
{% extends 'base.html' %}

{% block title %}
    {{articolo.titolo}}
{% endblock title %}

{% block content %}
    <h1>{{articolo.titolo}}</h1>
    <h3>{{ articolo.contenuto }}</h3>
    <h5>Autore: {{ articolo.giornalista }}</h5>
{% endblock content %}

news/templates/giornalista_detail.html
{% extends 'base.html' %}

{% block title %}
    {{giornalista.nome}} {{giornalista.cognome}}
{% endblock title %}

{% block content %}
    <h1>{{giornalista.nome}} {{giornalista.cognome}}</h1>
    <h3>{{ giornalista.anno_di_nascita }}</h3>
    {% for articolo in articolo %}
        <ul>
            <li>
                <p>Titolo: <a href={% url 'news:articolo_detail' articolo.id %}> {{articolo.titolo}}</a> - Visualizzazioni {{articolo.visualizzazioni}}</p>
            </li>
        </ul>
    {% endfor %}
{% endblock content %}

news/templates/homepage.html
{% extends 'base.html' %}
{%block title%}
    Articoli e Giornalisti
{%endblock title%}
{%block title%}
    <h4>Articoli:</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo:</strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto:</strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore:</strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    <h4>Giornalisti:</h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome:</strong>{{ giornalista.nome }}</p>
            <p><strong>Cognome:</strong>{{ giornalista.cognome }}</p>
            <hr>
        {% endfor %}
{%endblock content%}

news/templates/homepage_news.html
{% extends 'base.html' %}
{%block title%}
    Articoli e Giornalisti
{%endblock title%}
{%block content%}
    <h4>Articoli:</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo:</strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto:</strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore:</strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    <h4>Giornalisti:</h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome:</strong>{{ giornalista.nome }}</p>
            <p><strong>Cognome:</strong>{{ giornalista.cognome }}</p>
            <hr>
        {% endfor %}
{%endblock content%}

news/templates/index_news.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Index news {%endblock title%}

{%block content%}
    <h1>Index news</h1>
    <li><a href="{% url 'index'%}">Index</a></li>
    <li><a href="{% url 'news:homepage_news'%}">Homepage</a></li>
    <li><a href="{% url 'news:lista_articoli'%}">Lista articoli</a></li>
    <li><a href="{% url 'news:lista_giornalisti'%}">Lista giornalisti</a></li>
    <li><a href="{% url 'news:query_base'%}">Query</a></li>
{%endblock content%}

news/templates/lista_articoli.html
{% extends 'base.html' %}

{% block title %}
    Articoli
{% endblock title %}    

{% block content %}
    <h1>Articoli</h1>
    {% for articolo in articoli %}
        <p><strong>Titolo: </strong>
            <a href="/news/articoli/{{articolo.id}}">{{articolo.titolo}}</a>
        </p>
        <p><strong>Contenuto: </strong>
            {{articolo.contenuto}}
        </p>
        <p><strong>Autore: </strong>
            <a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{articolo.giornalista}}</a>
        </p>
        <hr>
    {% endfor %}
{% endblock content %}

news/templates/lista_giornalisti.html
{% extends 'base.html' %}

{% block title %}
    Lista Giornalisti
{% endblock title %}    

{% block content %}
    {% for giornalista in giornalisti %}
        <p><strong>Nome: </strong>
            {{giornalista.nome}}
        </p>
        <p><strong>Cognome: </strong>
            {{giornalista.cognome}}
        </p>
        <hr>
    {% endfor %}
{% endblock content %}

news/templates/query_base.html
{% extends "base.html" %}
{%block title%} 
    Query Base
{%endblock title%}
{%block content %}
    <h1>Risultati delle Query</h1>

    <h6>Query 1: Articoli di giornalisti con cognome 'Marinelli'</h6>
    <ul>
        {% for articolo in articoli_cognome %}
            <li>{{ articolo.titolo }}</li>
        {% endfor %}
    </ul>

    <h6>Query 2: Numero totale di articoli</h6>
    <p>{{ numero_totale_articoli }}</p>

    <h6>Query 3: Numero di articoli scritti dal giornalista con ID 4</h6>
    <p>{{ numero_articoli_giornalista_1 }}</p>

    <h6>Query 4: Articoli ordinati per numero di visualizzazioni (decrescente)</h6>
    <ul>
        {% for articolo in articoli_ordinati %}
            <li>{{ articolo.titolo }} - Visualizzazioni: {{ articolo.visualizzazioni }}</li>
        {% endfor %}
    </ul>

    <h6>Query 5: Articoli senza visualizzazioni</h6>
    <ul>
        {% for articolo in articoli_senza_visualizzazioni %}
            <li>{{ articolo.titolo }}</li>
        {% endfor %}
    </ul>

    <h6>Query 6: Articolo più visualizzato</h6>
    <p>{{ articolo_piu_visualizzato.titolo }} - Visualizzazioni: {{ articolo_piu_visualizzato.visualizzazioni }}</p>

    <h6>Query 7: Giornalisti nati dopo il 1900</h6>
    <ul>
        {% for giornalista in giornalista_data %}
            <li>{{ giornalista.nome }} {{ giornalista.cognome }}</li>
        {% endfor %}
    </ul>
        

    <h6>Query 8: Articoli pubblicati il 1 gennaio 2023</h6>
    <ul>
        {% for articolo in articoli_del_giorno %}
            <li>{{ articolo.titolo }}</li>
        {% endfor %}
    </ul>

    <h6>Query 9: Articoli pubblicati nel 2023</h6>
    <ul>
        {% for articolo in articoli_periodo %}
            <li>{{ articolo.titolo }}</li>
        {% endfor %}
    </ul>


    <h6>Query 10: Articoli scritti da giornalisti nati prima del 1980</h6>
    {% if articoli_giornalisti %}
            {% for articolo in articoli_giornalisti %}
                <li>{{ articolo.titolo }} - Scritto da {{ articolo.giornalista.nome }} {{ articolo.giornalista.cognome }}</li>
            {% endfor %}
    {% else %}
        <p>Tutti i giornalisti sono nati dopo il 1980</p>
    {% endif %}


    <h6>Query 11: Giornalista più giovane</h6>
    <p>{{ giornalista_giovane.nome }} {{ giornalista_giovane.cognome }} {{giornalista_giovane.anno_di_nascita}}</p>

    <h6>Query 12: Giornalista più anziano</h6>
    <p>{{ giornalista_anziano.nome }} {{ giornalista_anziano.cognome }} {{giornalista_anziano.anno_di_nascita}}</p>

    <h6>Query 13: Ultimi 5 articoli pubblicati</h6>
    <ul>
        {% for articolo in ultimi %}
            <li>{{ articolo.titolo }}</li>
        {% endfor %}
    </ul>

    <h6>Query 14: Articoli con almeno 100 visualizzazioni</h6>
    <ul>
        {% for articolo in articoli_minime_visualizzazioni %}
            <li>{{ articolo.titolo }} - Visualizzazioni: {{ articolo.visualizzazioni }}</li>
        {% endfor %}
    </ul>

    <h6>Query 15: Articoli che contengono la parola 'importante' nel titolo</h6>
    <ul>
        {% for articolo in articoli_parola %}
            <li>{{ articolo.titolo }}</li>
        {% endfor %}
    </ul>

    <h6>Query 16: Articoli pubblicati in un certo mese di  un anno specifico</h6>
    <ul>
        {% if articoli_mese_anno %}
            {% for articolo in articoli_mese_anno %}
                <li>{{ articolo.titolo }}</li>
            {% endfor %}
        {% else %}
            <p>Nessun articolo è stato pubblicato in questo mese</p>
        {% endif %}
    </ul>

    <h6>Query 17: giornalisti con almeno un articolo con più di 100 visualizzazioni</h6>
    <ul>
        {% for giornalista in giornalisti_con_articoli_popolari %}
            <li>{{ giornalista.nome }} {{ giornalista.cognome }}</li>
        {% endfor %}
    </ul>

    <h6>Query 18: Articoli che vengono selezionati con la condizione AND</h6>
    <ul>
        {% for articolo in articoli_con_and %}
            <li>{{articolo.titolo}}</li>
        {% endfor %}
    </ul>

    <h6>Query 19: Articoli che vengono selezionati con la condizione OR</h6>
    <ul>
        {% for articolo in articoli_con_or %}
            <li>{{articolo.titolo}}</li>
        {% endfor %}
    </ul>

    <h6>Query 20: Articoli che vengono selezionati con la condizione NOT</h6>
    <ul>
        {% for articolo in articoli_con_not %}
            <li>{{articolo.titolo}}</li>
        {% endfor %}
    </ul>

    
{%endblock content%}